### ISSUE TITLE
Define list of features

### ISSUE THREAD

**Issue by candanedo** [albertm805/magmalabs-estimator#38]
## Description
- As a product owner. Define the list of features that are going to be part of the website (Meaning all the products that a client can choose from).

## Requirements
- It must be reviewed and approved by the product owner.

## Acceptance criteria.
- It must include the names, characteristics, punctuation, and dependencies with other features.

**Comment by candanedo** [comment]
###Description
- As a product owner. Define all the features that are going to be included in the project (meaning all the products that are going to be available for the clients to choose).
###Requirements
- The list must be reviewed and approve by the product owner.
###Link

###Acceptance criteria.
- For now, it's enough to just have the footer with no hero images.

**Comment by Tachoramirez** [comment]
Ecommerce
* Homepage
    * Hero Section with Slider
    * Recently added
    * Popular items
    * Brands slider
    * Featured Categories
    * Structured Data (Rich snippets)
    * Newsletter subscription
* Categories Page
    * Facets (Filters)
        * Subcategories
        * Brand
        * Price
        * One custom property
    * Hero Section
    * Pagination
* Category Detail Page
    * Children categories with featured content
* Product Detail page
    * High res images
    * Multiple Variants
    * Structured Data
    * Recently viewed products
    * Recommended Products
    * Sale price
* Search
    * Fulltext search
    * Facets
        * Category
        * Brand
    * Pagination
* Brand Detail Page
    * Facets (Filters)
        * Categories
        * Colors
        * Price
        * One custom property
    * Featured Content
    * Most popular 
* Brands Page
    * Brands slider with featured content
    * Hero section by brand
* Checkout
    * 4 steps checkout
        * Address
        * Shipping Method
            * Free shipping thresholds
        * Payment Method
            * Paypal Express
            * Banorte
            * Oxxo
            * Promo codes
                * Flat discount
                * Percentage discount
        * Confirm
    * Enhanced eCommerce integration (GA)
* Static Pages
    * About us
    * Terms & Conditions
    * Privacy
    * Careers
    * Returns Policy
* Top Navigation
    * Search
    * Categories Menu
* API
    * Categories
    * Products
    * Orders
    * Users
* Integrations
    * Amazon Marketplace
        * Sync catalog
        * Sync inventory
        * Pull new orders from Amazon
        * Push order shipment status to Amazon
    * Multiple Stock Locations
    * CMS
        * Manage featured content
        * Blog engine
    * ERP
        * Sync Inventory
        * Sync Orders
    * Electronic Invoice

--Cada feature tendrá puntuación de 2pts
--La dependencia será su clase padre (Según el product owner)
